In [133]:
import numpy as np

In [134]:
left, up, dia = 1, 2, 3
match, mismatch, insert, delete = 2, -1, -1, -1

In [135]:
def delta(a, b):
    if a == b:
        return match
    if '-' == a:
        return insert
    if '-' == b:
        return delete
    return mismatch

In [136]:
def node_score(s, t, node, i, j):
    score_match_mismatch = node[i-1, j-1] \
        + delta(s[i], t[j])
    score_delete = node[i-1, j] + delta(s[i], '-')
    score_insert = node[i, j-1] + delta(s[i], '-')
    return max([score_match_mismatch, 
                score_delete, 
                score_insert])

In [137]:
def lsc(s, t):
    n = len(s)
    m = len(t)
    backtrack = np.zeros((n+1, m+1), dtype=int)
    v = np.zeros((n+1, m+1), dtype=int)
    s = '-' + s
    t = '-' + t
    for i in range(n+1):
        v[i, 0] = -i
    for j in range(m+1):
        v[0, j] = -j
    for i in range(1, n+1):
        for j in range(1, m+1):
            v[i, j] = node_score(s, t, v, i, j)
            if v[i, j] == v[i-1, j] + delta(s[i], '-'):
                backtrack[i, j] = up
            elif v[i, j] == v[i, j-1] + delta('-', t[j]):
                backtrack[i, j] = left
            else:
                backtrack[i, j] = dia
    return v, backtrack

In [138]:
s = 'ACAATCC'
t = 'AGCATGC'

v, backtrack = lsc(s, t)
print(v)
print(backtrack)

[[ 0 -1 -2 -3 -4 -5 -6 -7]
 [-1  2  1  0 -1 -2 -3 -4]
 [-2  1  1  3  2  1  0 -1]
 [-3  0  0  2  5  4  3  2]
 [-4 -1 -1  1  4  4  3  2]
 [-5 -2 -2  0  3  6  5  4]
 [-6 -3 -3  0  2  5  5  7]
 [-7 -4 -4 -1  1  4  4  7]]
[[0 0 0 0 0 0 0 0]
 [0 3 1 1 1 1 1 1]
 [0 2 3 3 1 1 1 1]
 [0 2 2 2 3 1 1 1]
 [0 2 2 2 2 3 1 1]
 [0 2 2 2 2 3 1 1]
 [0 2 2 3 2 2 3 3]
 [0 2 2 2 2 2 2 3]]


In [139]:
def out(s, t, backtrack):
    n = len(s)
    m = len(t)
    source, target = s, t
    i, j = n, m
    while i > 0 and j > 0:
        if backtrack[i, j] == left:
            source = source[:j-1] + '-' + source[j-1:]
            j = j - 1
            continue
        if backtrack[i, j] == up:
            target = target[:i-1] + '-' + target[i-1:]
            i = i - 1
            continue
        i = i - 1
        j = j - 1
    return source, target

In [140]:
source, target = out(s, t, backtrack)
print(source)
print(target)

A-CAATCC
AGC-ATGC
